tasks:
  - init: pip install -r requirements.txt
  - command: code --install-extension kyntrack.python-test
  - command: for i in {1..6}; do chmod 600 ~/.ssh/id_rsa && chmod 644 ~/.ssh/id_rsa.pub && ssh-keyscan github.com >> ~/.ssh/known_hosts; sleep 20; done
  - command: git remote set-url origin git@github.com:gitpoduser01/gitpoduser01-LLMI-CL-HELLOLLM-1.git && sed "s/\r$//" commit-command.sh | bash